# Generated by Django 5.1.1 on 2024-09-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileupload", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_size",
            field=models.IntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
